# Generated by Django 3.0.6 on 2020-05-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('gid', models.CharField(editable=False, max_length=31, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('gid', models.CharField(editable=False, max_length=31, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('gid', models.CharField(editable=False, max_length=31, primary_key=True, serialize=False)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana_app.Assignee')),
            ],
        ),
    ]
