# Generated by Django 3.0.6 on 2020-05-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asana_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignee',
            new_name='UserModel',
        ),
    ]
