# Generated by Django 3.0.6 on 2020-05-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana_app', '0002_auto_20200517_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='name',
            field=models.CharField(default='', editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
