# Generated by Django 3.0.6 on 2020-05-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asana_app', '0004_auto_20200518_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='asana_app.ProjectModel'),
            preserve_default=False,
        ),
    ]
